### ISSUE TITLE
Whitelist and Blacklist local file

### ISSUE THREAD

**Issue by mrzhoul-1** [ragibkl/adblock-dns-server#11]
Which file need to be modified to add my domain for blacklist or whitelist. why not you add sync.sh script that can add blacklist.txt and whitelist.txt to your generated hosts.adblock locally. Lastly... in the end of start.sh or i dont know how docker works. run the migration of whitelist.txt and blacklist.txt to hosts.adblock locally

**Comment by ragibkl** [comment]
Hi @mrzhoul-1 , thanks for reaching out.

You are right. The current local `start.sh` script does not allow you to add/remove your own blacklist/whitelist.

I am adding some example scripts to support that now. https://github.com/ragibkl/adblock-dns-server/pull/14/files
I'm merging this change for now.

In order to try it out, please pull/clone the latest version of this code, and follow the updated instructions on the readme file. Of course, you should only have 1 version running at any time, so run the original stop script if you haven't already.

Please help me test if it works in your case, and report back here.

**Comment by ragibkl** [comment]
Hi @mrzhoul-1 ,

Do test this out, and let me know if any issues. I'd like to close this issue if it's fixed.

**Comment by ragibkl** [comment]
I think will close this issue now, since the requested functionality has been added in latest master.
