### ISSUE TITLE
Does lists update regularly?

### ISSUE THREAD

**Issue by Tomatoide** [ragibkl/adblock-dns-server#132]
Hi @ragibkl 
So there is a false positive in one of the lists that was added and fixed on the same day (april 30) by the list maintainer but is still blocked by bancuh which makes me suspect that lists don't update or something is broken?
the list is oisd 
the site is amazon.eg
Thank you

**Comment by ragibkl** [comment]
You can check the list of our build jobs here: https://gitlab.com/ragibkl/adblock-dns-server/-/jobs

After your last code push, it ran here: https://gitlab.com/ragibkl/adblock-dns-server/-/jobs/2398343881

The servers are setup so that when a new docker image is available, it will pull the latest image and run that. However, image pull doesn't happen immediately, for now I think it is only once every 5 minutes. If you don't see results immediately, maybe wait for a bit to see it.

I checked the servers in France just now. Seems like the image was pulled 6 days ago. Exactly after the build success.
![image](https://user-images.githubusercontent.com/18181377/167223702-8d5490e2-7a10-4d3f-9947-b930a7669b2b.png)

I think, our pipeline is working fine.

Regarding the broken site, it must mean that there's another list that's blocking that site.

**Comment by Tomatoide** [comment]
So, from what I understand, there is no mechanism to update blocklists unless you do a complete build job, is that correct?
If that is the case, it explains why the site is still blocked by bancuh because it's still using outdated list before it was fixed in recent update

**Comment by ragibkl** [comment]
Yeah, but the build job triggers automatically every time we merge a pull request, or push new codes to master. When we merged your Pull Request on April 30th, it ran the build automatically. The servers should then pick up your new list 5 minutes after that.

**Comment by ragibkl** [comment]
Owh, I think I misunderstand you. You mean if the upstream list maintainer updates their list?

I actually did have a thought on this use case. There is a way to configure the dns servers, so that it regularly pulls the config down directly from upstream lists, and automatically updates itself. We can set the interval to be every 1 hour.

Code samples are already here: https://github.com/ragibkl/adblock-dns-server/tree/master/dns_self-update. I probably just need to change a couple of lines here and there.

I never went with this method, because the current method already works.

Do you think we should try this method instead?

**Comment by Tomatoide** [comment]
> Owh, I think I misunderstand you. You mean if the upstream list maintainer updates their list?
> 
> I actually did have a thought on this use case. There is a way to configure the dns servers, so that it regularly pulls the config down directly from upstream lists, and automatically updates itself. We can set the interval to be every 1 hour.
> 
> Code samples are already here: https://github.com/ragibkl/adblock-dns-server/tree/master/dns_self-update. I probably just need to change a couple of lines here and there.
> 
> I never went with this method, because the current method already works.
> 
> Do you think we should try this method instead?

Yes I think this would be a great improvement, lets try it

**Comment by Tomatoide** [comment]
Hi, @ragibkl any news on this? I think an interval of 24h would be good

**Comment by ragibkl** [comment]
Hi @Tomatoide ,

Sorry about this. I haven't had the time to work on this. I'll find some time to make progress on this. Let me set a goal, maybe I try get it done in 2 weeks max.

**Comment by ragibkl** [comment]
Hi @Tomatoide ,

PR: https://github.com/ragibkl/adblock-dns-server/pull/149
It is deployed to all servers. @Tomatoide , please let me know if France servers have any issues at all in the next few days.

**Comment by Tomatoide** [comment]
Nice thank you I will test servers next few days they seem to be working fine
