### ISSUE TITLE
Response the speed of your DNS while using

### ISSUE THREAD

**Issue by phanluchoa** [ragibkl/adblock-dns-server#32]
Hello @ragibkl again,

Today I want to talk you about the response time to the website that I go with. When I use your DNS to access to any my livestream game websites. I received that your DNS load very slow to open my website. This is some my websites that I use to watch livestream games: https://nimo.tv ; https://nonolive.com and http://bigo.sg. That are some website that I usually use to watch livestream games. All of them its load so slow when using your adblock dns, sometimes they cannot load to website and notification the website not working. Can you review and solve the problem I have received !!!

https://drive.google.com/file/d/17jLXP0dlCf6QtuKaIMtvwWaqH5UkRVc_/view?usp=drivesdk

Thanks you !!!

**Comment by phanluchoa-accounttest** [comment]
> Hello @ragibkl again,
> 
> Today I want to talk you about the response time to the website that I go with. When I use your DNS to access to any my livestream game websites. I received that your DNS load very slow to open my website. This is some my websites that I use to watch livestream games: https://nimo.tv ; https://nonolive.com and http://bigo.sg. That are some website that I usually use to watch livestream games. All of them its load so slow when using your adblock dns, sometimes they cannot load to website and notification the website not working. Can you review and solve the problem I have received !!!
> 
> https://drive.google.com/file/d/17jLXP0dlCf6QtuKaIMtvwWaqH5UkRVc_/view?usp=drivesdk
> 
> Thanks you !!!

I fix some error of my issue: bigo.tv not bigo.sg !! http://bigo.sg 👉 https://bigo.tv

thanks

**Comment by ragibkl** [comment]
Hi @phanluchoa ,

I tried opening all 3 websites. No issues. I saw the video you shared but I don't know which website or app you are opening in the video. Please let me know more detail (which app? website?), so I can try to test the same issue. Also seems like you are using mobile phone. Can you please test with laptop as well? Laptop using Chrome or Firefox can give more details.

I tried checking their dns and IP data:
- nimo.tv
  - TTL: 60 seconds
  - Location: Ashburn, Virgina, USA
- nonolive.com
  - TTL: 60 seconds
  - Location: Ashburn, Virgina, USA
- bigo.tv
  - TTL: 5 minutes
  - Location: Diamond Bar, California, USA

For `nimo.tv` and `nonolive.com`, it seems that they use very short TTL configuration. Usually dns records are re-used on subsequent web page load. They are only refresh after 1 hour. But this config means that we need to refresh every 60 seconds. This might be reason why it is slow.

However, I think that the websites are slow because the servers are located far away. We are in south east asia, it might be slow to access websites in the USA.

**Comment by phanluchoa** [comment]
@ragibkl Hello,

Can you review my issue #31 ??

**Comment by phanluchoa** [comment]
@ragibkl Ok for now, the response about the speed load website of your DNS its ok for now. Because your DNS located in Asia not in USA so access to any website in usa its slow. Its Ok, you can close this comment and solve the issue in #31 !!! Thanks you

**Comment by ragibkl** [comment]
@phanluchoa , can you help me test my dns performance?
```
# Bancuh DNS 1 & 2
time nslookup bigo.tv 139.59.219.245 > null 
time nslookup bigo.tv 139.59.218.207 > null 

# Google DNS
time nslookup bigo.tv 8.8.8.8 > null 
```
This only works on Linux and Mac though. Let me know the output.

Also, do you still experience the slowness? Or do you have any other clue of the slowness?
So far from my testing, the websites are working fine.

**Comment by phanluchoa** [comment]
@ragibkl Your DNS work still slow for me but its ok because your dns located in asia

**Comment by phanluchoa-accounttest** [comment]
@ragibkl you can close the issue now
