### ISSUE TITLE
Quick thanks

### ISSUE THREAD

**Issue by alexwilczewski** [ragibkl/adblock-dns-server#4]
Pardon me posting an issue, I'm just stopping by to say thank you. I was in the mood to create a DNS server and your code helped me get started. I created a whitelist mechanism in my fork if you're interested in further development.

**Comment by ragibkl** [comment]
Hi @alexwilczewski 

You are most welcome.
I never thought about a use case for whitelisting before, that sounds very interesting.
I don't think I will continue work on this any time soon, but perhaps I'll look at your additions.

Really sorry for the late reply, I didn't notice the issue created.

**Comment by ragibkl** [comment]
Hi @alexwilczewski ,

Turns out that months after I said that, I did some major refactoring on my code base. I also used your dockerfile templates to help me as well.

Thanks to your idea for whitelisting, I also implemented a whitelist on my code base.

Thank you for the suggestions!!! Much appreciated.
