### ISSUE TITLE
Bancuh has DNS leaks?  

### ISSUE THREAD

**Issue by TechComputerServiceDunkerque** [ragibkl/adblock-dns-server#57]
Hello, 

I have just noticed thanks to a site that tests leaks in that there were many leaks coming from Bancuh to Google &  is this normal? 

I'll let you take the test: https://browserleaks.com/ip

Is it possible to put the FDN servers that are anonymous for France in place of Cloudflare's if you don't mind, so the service will be more secure for the French? Because I just found out that Cloudflare is selling our data.

https://www.fdn.fr/actions/dns/

s0.fdn.fr : 80.67.169.12 ou 2001:910:800::12
ns1.fdn.fr : 80.67.169.40 ou 2001:910:800::40

**Comment by ragibkl** [comment]
Hi @TechComputerServiceDunkerque 

All my dns servers proxies dns requests to external servers.
The servers in singapore and tokyo proxy to google dns `8.8.8.8` and `8.8.4.4`.
The server in France proxies to cloudflare dns `1.1.1.1` and `1.0.0.1`

In both cases, they may establish the relationship between web activity on a domain name (website) and an IP address. However, because the dns requests are proxied, they will only associate with the IP addresses of my servers. They should not see your personal home/device IP address. The privacy risk should be low.

The test should show that you are using CloudFlare as ISP. If not, then maybe I made a mistake in configuration.

At any rate, I don't mind to change the France server to use FDN dns providers. You seem to recommend them highly. Let's try them.

**Comment by ragibkl** [comment]
I've applied the change. Please test it on your side and let me know.

In the future, I may want to stop proxying the dns requests, and operate in full resolver mode. We'll see how it goes.

Also, please note that you are still using my dns servers. You have to trust that I don't log your dns activity when using my servers. If DNS privacy is a concern, I encourage people to deploy their own dns servers and share with friends and family.

Personally, I deploy dns servers to help people. I don't log user activities. I also don't know who is using what IP address.

**Comment by TechComputerServiceDunkerque** [comment]
Thanks for the work, sincerely I don't think you take the information, I just know Google does ^^.  Otherwise the tests are conclusive, I'm very satisfied with your server.

**Comment by TechComputerServiceDunkerque** [comment]
Hello, 

I have noticed some cuts with the dns of fdn, is it possible to change the dns by the french dns 93.23.127.149 . Thank you, I am really satisfied with your services and so are my friends.

**Comment by ragibkl** [comment]
Hi @TechComputerServiceDunkerque , I'm not sure what you mean by cuts. Do you mean sometimes the dns is not responding?

If so, this is probably due to the current adblock dns update process. They way it works right now, there is a 2 - 3 minutes downtime during updates. If that is what you are experiencing, than it's because of my dns server, not FDN servers.

**Comment by TechComputerServiceDunkerque** [comment]
Hello, I'm talking about internet downtime.

**Comment by ragibkl** [comment]
Hi, I think the downtime is due to my own DNS server update process. As I said, right now the DNS has to stop, and start again with new list every time we update blacklist/whitelist. Downtime of ~3 minutes is expected.

I don't know yet how I can make the update process with no downtime. I've created a separate issue ticket to track if I can progress this here: https://github.com/ragibkl/adblock-dns-server/issues/58.
